### PR TITLE
Phony update with tests

### PR DESCRIPTION
**Pull request by dmi3y**
Update is irrelevant, resistance is futile.

### CODE REVIEW

**Comment by dmi3y** [comment]
GItHub does not like rebase

**Comment by dmi3y** [comment]
Hold off for a wile

**Comment by incrediblesound** [comment]
Haha we were working on this at the same time! Crazy :-)

**Comment by dmi3y** [comment]
Update? It seems because everything is by reference it is hard to wrap head around. Anyways this is an attempt.

And it is not work, it is fun :D

**Comment by incrediblesound** [comment]
Yes! It is crazy! All records _inside_ the database are by reference. If you mutate the record in one place it will be reflected in all the indexes. All records return by queries, however, are copied and therefore will not affect the database.

**Comment by dmi3y** [comment]
Cool, I see the new update. PR is offline!

**Pull request closed without merging**
